# VacationPy
----

#### Note
* Keep an eye on your API usage. Use https://developers.google.com/maps/reporting/gmp-reporting as reference for how to monitor your usage and billing.

* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [1]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os

# Import API key
from api_keys import g_key

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [2]:
#import csv and store into a dataframe
weather_df = pd.read_csv('Weather_df.csv', index_col=0)

weather_df.head()

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
0,Dunedin,-45.8742,170.5036,58.80,85,100,17.00,NZ,1645505259
1,Bandarbeyla,9.4942,50.8122,78.21,74,47,15.77,SO,1645505265
2,Yangi Marg`ilon,40.4272,71.7189,47.62,45,100,2.30,UZ,1645505270
3,Esperance,-33.8667,121.9000,91.24,42,1,8.34,AU,1645505276
4,Narsaq,60.9167,-46.0500,-1.98,70,97,6.13,GL,1645505282

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [3]:
#store lat, lng into a variable
cities = weather_df[['Lat', 'Lng']]

#store humidity into a variable
humidity = weather_df['Humidity']

In [25]:
fig = gmaps.figure()

heat_layer = gmaps.heatmap_layer(cities, weights = humidity,
                                 dissipating=False, max_intensity=700,
                                 point_radius=10)

fig.add_layer(heat_layer)

fig

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [29]:
#Use conditionals on max temp to find desired weather conditions
vacay_destinations_df = weather_df[(weather_df['Max Temp']<80) & 
                                   (weather_df['Max Temp']< 70) & 
                                   (weather_df['Wind Speed'] < 10) & 
                                   (weather_df['Cloudiness'] == 0)]

vacay_destinations_df

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
15,Upington,-28.4478,21.2561,59.38,55,0,3.44,ZA,1645505342
39,East London,-33.0153,27.9116,65.34,88,0,8.05,ZA,1645505483
47,Port Elizabeth,-33.9180,25.5701,57.49,88,0,5.75,ZA,1645505260
62,Kidal,18.4411,1.4078,67.37,12,0,9.73,ML,1645505618
65,Coyhaique,-45.5752,-72.0662,51.75,54,0,5.75,CL,1645505170
67,Magadan,59.5667,150.8000,3.90,80,0,6.06,RU,1645505646
72,Taiyuan,37.8694,112.5603,33.66,19,0,4.47,CN,1645505678
102,Cape Town,-33.9258,18.4232,63.27,77,0,8.05,ZA,1645505460
133,Nongpoh,25.9000,91.8833,62.17,35,0,5.55,IN,1645506047
152,Bethel,41.3712,-73.4140,39.33,73,0,0.00,US,1645506165
159,Nogales,31.3086,-110.9422,49.08,56,0,3.44,MX,1645506209
162,Coquimbo,-29.9533,-71.3436,60.53,88,0,4.61,CL,1645506225
172,Los Llanos de Aridane,28.6585,-17.9182,55.15,76,0,8.05,ES,1645506285
174,Westport,41.1415,-73.3579,40.19,82,0,4.61,US,1645506296
197,Onda,39.9667,-0.2500,51.71,33,0,7.00,ES,1645508330
226,Arman',59.7000,150.1667,4.95,78,0,8.39,RU,1645509402
253,Comodoro Rivadavia,-45.8667,-67.5000,53.06,56,0,7.11,AR,1645509764
258,Pavlodar,52.3000,76.9500,15.60,79,0,6.71,KZ,1645510063
272,Kumul,42.8000,93.4500,38.37,25,0,3.22,CN,1645510151
308,Evensk,61.9500,159.2333,-11.78,81,0,7.96,RU,1645510373
309,Saldanha,-33.0117,17.9442,63.28,79,0,8.86,ZA,1645510379
344,Sterling,39.0062,-77.4286,52.16,63,0,6.91,US,1645510587
351,Marrakesh,31.6315,-8.0083,53.67,43,0,6.91,MA,1645510630
368,Granada,37.2500,-3.2500,44.29,37,0,3.69,ES,1645510728
370,Renqiu,38.6989,116.0936,33.78,26,0,5.79,CN,1645510739
380,Sitka,57.0531,-135.3300,30.09,64,0,6.91,US,1645510794
390,Arlit,18.7369,7.3853,63.23,10,0,6.04,NE,1645510850
403,Vallenar,-28.5708,-70.7581,64.18,65,0,1.03,CL,1645510931
455,Kimberley,-28.7323,24.7623,69.49,40,0,3.44,ZA,1645511247
462,Ancud,-41.8697,-73.8203,50.43,80,0,7.96,CL,1645511290
477,Korla,41.7597,86.1469,36.90,33,0,2.13,CN,1645511382
491,Östersund,63.1792,14.6357,12.65,100,0,8.05,SE,1645511464
501,Alhama de Murcia,37.8510,-1.4251,53.96,27,0,6.51,ES,1645511530
504,Umeå,63.8284,20.2597,6.73,85,0,6.91,SE,1645511547
531,Sarkand,45.4100,79.9186,38.26,94,0,0.56,KZ,1645511696
534,Aguascalientes,21.8833,-102.3000,57.90,40,0,8.05,MX,1645511518
535,La Ronge,55.1001,-105.2842,-30.75,68,0,3.44,CA,1645511718

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [7]:
#Use location to create hotel_df
hotel_df = vacay_destinations_df[['City','Lat', 'Lng', 'Country']].copy()
#add hotel name as a column to hotel_df
hotel_df['Hotel Name']= ''

hotel_df

                      City      Lat       Lng Country Hotel Name
15                Upington -28.4478   21.2561      ZA
39             East London -33.0153   27.9116      ZA
47          Port Elizabeth -33.9180   25.5701      ZA
62                   Kidal  18.4411    1.4078      ML
65               Coyhaique -45.5752  -72.0662      CL
67                 Magadan  59.5667  150.8000      RU
72                 Taiyuan  37.8694  112.5603      CN
102              Cape Town -33.9258   18.4232      ZA
133                Nongpoh  25.9000   91.8833      IN
152                 Bethel  41.3712  -73.4140      US
159                Nogales  31.3086 -110.9422      MX
162               Coquimbo -29.9533  -71.3436      CL
172  Los Llanos de Aridane  28.6585  -17.9182      ES
174               Westport  41.1415  -73.3579      US
197                   Onda  39.9667   -0.2500      ES
226                 Arman'  59.7000  150.1667      RU
253     Comodoro Rivadavia -45.8667  -67.5000      AR
258               Pavlodar  52.3000   76.9500      KZ
272                  Kumul  42.8000   93.4500      CN
308                 Evensk  61.9500  159.2333      RU
309               Saldanha -33.0117   17.9442      ZA
344               Sterling  39.0062  -77.4286      US
351              Marrakesh  31.6315   -8.0083      MA
368                Granada  37.2500   -3.2500      ES
370                 Renqiu  38.6989  116.0936      CN
380                  Sitka  57.0531 -135.3300      US
390                  Arlit  18.7369    7.3853      NE
403               Vallenar -28.5708  -70.7581      CL
455              Kimberley -28.7323   24.7623      ZA
462                  Ancud -41.8697  -73.8203      CL
477                  Korla  41.7597   86.1469      CN
491              Östersund  63.1792   14.6357      SE
501       Alhama de Murcia  37.8510   -1.4251      ES
504                   Umeå  63.8284   20.2597      SE
531                Sarkand  45.4100   79.9186      KZ
534         Aguascalientes  21.8833 -102.3000      MX
535               La Ronge  55.1001 -105.2842      CA

In [8]:
# find the closesthotel of each type to coordinates

base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
params = {
    "radius": 5000,
    "types": "lodging",
    "key": g_key,
}
# use iterrows to iterate through pandas dataframe
for index, row in hotel_df.iterrows():
    lat=row['Lat']
    lng=row['Lng']
    
    params['location']= f'{lat},{lng}'

    # assemble url and make API request

    response = requests.get(base_url, params=params).json()
    #print(response)
    # extract results
    #response = response.json()
    
    try:

        
        hotel_df.loc[index, 'Hotel Name'] = response['results'][0]['name']

        
    except (KeyError, IndexError):
        print("Missing field/result... skipping.")
        
    print("------------")

------------
------------
------------
Missing field/result... skipping.
------------
------------
------------
------------
------------
------------
------------
------------
------------
------------
------------
------------
Missing field/result... skipping.
------------
------------
------------
------------
Missing field/result... skipping.
------------
------------
------------
------------
------------
------------
------------
------------
------------
------------
------------
------------
------------
------------
------------
------------
------------
------------

In [9]:
hotel_df

,City,Lat,Lng,Country,Hotel Name
15,Upington,-28.4478,21.2561,ZA,River Place Manor
39,East London,-33.0153,27.9116,ZA,Tu Casa
47,Port Elizabeth,-33.9180,25.5701,ZA,39 On Nile Guest House
62,Kidal,18.4411,1.4078,ML,
65,Coyhaique,-45.5752,-72.0662,CL,Diego De Almagro Coyhaique
67,Magadan,59.5667,150.8000,RU,Magadan hotel
72,Taiyuan,37.8694,112.5603,CN,Taiyuan Wanda Wenhua Hotel
102,Cape Town,-33.9258,18.4232,ZA,"Radisson Blu Hotel Waterfront, Cape Town"
133,Nongpoh,25.9000,91.8833,IN,Bei sumer cottage
152,Bethel,41.3712,-73.4140,US,Courtyard by Marriott Danbury
159,Nogales,31.3086,-110.9422,MX,Siesta Motel
162,Coquimbo,-29.9533,-71.3436,CL,Hotel San Juan
172,Los Llanos de Aridane,28.6585,-17.9182,ES,Valle Aridane
174,Westport,41.1415,-73.3579,US,The Inn at Longshore
197,Onda,39.9667,-0.2500,ES,Motel Shhh
226,Arman',59.7000,150.1667,RU,
253,Comodoro Rivadavia,-45.8667,-67.5000,AR,Austral Hotel
258,Pavlodar,52.3000,76.9500,KZ,Sary Arka
272,Kumul,42.8000,93.4500,CN,Laoyutang Resort
308,Evensk,61.9500,159.2333,RU,
309,Saldanha,-33.0117,17.9442,ZA,Blue Bay Lodge
344,Sterling,39.0062,-77.4286,US,Hampton Inn & Suites Washington-Dulles Interna...
351,Marrakesh,31.6315,-8.0083,MA,Les Jardins de La Koutoubia
368,Granada,37.2500,-3.2500,ES,área autocaravanas La Peza
370,Renqiu,38.6989,116.0936,CN,City Garden Renqiu Meishicheng Store
380,Sitka,57.0531,-135.3300,US,Westmark Sitka
390,Arlit,18.7369,7.3853,NE,Case de Passage De la Prefecture
403,Vallenar,-28.5708,-70.7581,CL,Humacao Bed & Breakfast
455,Kimberley,-28.7323,24.7623,ZA,Welgewandel Guesthouse
462,Ancud,-41.8697,-73.8203,CL,Hotel Arena Gruesa
477,Korla,41.7597,86.1469,CN,Gulisitan Hotel
491,Östersund,63.1792,14.6357,SE,Best Western Hotel Gamla Teatern
501,Alhama de Murcia,37.8510,-1.4251,ES,Hotel Los Bartolos - Inicio Reservas
504,Umeå,63.8284,20.2597,SE,ProfilHotels | Aveny
531,Sarkand,45.4100,79.9186,KZ,Гостиница Сарканд
534,Aguascalientes,21.8833,-102.3000,MX,Hotel Francia Aguascalientes
535,La Ronge,55.1001,-105.2842,CA,Northland Motor Hotel

In [10]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Lat", "Lng"]]

In [11]:
# Add marker layer ontop of heat map


# Display figure
# Assign the marker layer to a variable
markers = gmaps.marker_layer(locations,info_box_content = hotel_info)
# Add the layer to the map
fig.add_layer(markers)
fig

Figure(layout=FigureLayout(height='420px'))